apiVersion: v1
kind: Service
metadata:
  labels:
   name: cassandra
  name: cassandra
spec:
  clusterIP: None
  selector:
    name: cassandra
  ports:
  - port: 9042
    targetPort: 9042

---
# kubectl scale rc cassandra --replicas=2
# kubectl exec -it cassandra-kmsph -- nodetool status
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
   name: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
     name: cassandra
  template:
    metadata:
      labels:
       name: cassandra 
    spec:
      containers:
         - name: cassandra
           command:
           - /run.sh
           resources:
            limits:
             cpu: "500m"
           env: 
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
               fieldRef:
                fieldPath: metadata.namespace 
           image: gcr.io/google_containers/cassandra:v5
           ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
           volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
