---
# kubectl create -f tomcat-rc.yaml
# kubectl get pod -l app=tomcatwebapp -o yaml | findstr podIP
# 可以用以下命令通过RC快速创建Service
# kubectl expose rc tomcatwebapp
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcatwebapp
spec:
  replicas: 2
  selector:
    app: tomcatwebapp
  template:
    metadata:
      name: tomcatwebapp
      labels:
        app: tomcatwebapp
    spec:
      containers:
        - name: tomcatwebapp
          image: tomcat
          ports:
            - containerPort: 8080
