---

apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: highest-priority
value: 1000000
globalDefault: false
description: "this priority class should be used for *** service pods only"

