---
# 容器程序获取pod及resource信息的方式
apiVersion: v1
kind: Pod
metadata:
 name: dapi-test-pod
spec:
 containers:
 - name: test-container
   image: busybox
   command: ["/bin/sh","-c","env"]
   resources:
    limits:
     cpu: "100m"
     memory: "128Mi"
    requests:
     cpu: "100m"
     memory: "128Mi"       
   env:
    - name: MY_POD_NAME
      valueFrom:
       fieldRef:
        fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
       fieldRef:
        fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
       fieldRef:
        fieldPath: status.podIP
    - name: MY_CPU_REQUEST
      valueFrom:
       resourceFieldRef:
         resource: requests.cpu
         containerName: test-container
    - name: MY_CPU_LIMIT
      valueFrom:
       resourceFieldRef:
        resource: limits.cpu
        containerName: test-container
    - name: MY_MEM_REQUEST 
      valueFrom:
       resourceFieldRef:
        containerName: test-container
        resource: requests.memory
    - name: MY_MEM_LIMIT
      valueFrom:
       resourceFieldRef:
        containerName: test-container
        resource: limits.memory
   livenessProbe:
       httpGet:
        path: /health
        port: 80
       initialDelaySeconds: 30
       timeoutSeconds: 2
 restartPolicy: Never