---
# kubectl label nodes aks-nodepool1-38582400-vmss000000 key1=a
# kubectl get pod -o wide
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    app: redis-master
  template:
    metadata:
      name: redis-master
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis-master
          image: kubeguide/redis-master
          ports:
            - containerPort: 6379
      nodeSelector:
        key1: a
