---
# kubectl create -f nginx-deployment.yaml --record
# kubectl get deployments
# kubectl get rs
# kubectl get pods
# kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
