---
#kubectl config set-context --current --namespace=default
#kubectl create -f cm-appvars.yaml
#kubectl get configmap
#kebuctl describe configmap cm-appvars
#kubectl get configmap cm-appvars -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-appvars
data:
  apploglevel: info
  appdatadir: /ver/data
