apiVersion: v1
kind: Service
metadata:
  name: dotnetcoredemo
spec:
  selector:
    app: dotnetcoredemo
  type: LoadBalancer 
  ports:
  - port: 8083
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcoredemo
spec:
  selector:
    matchLabels:
      app: dotnetcoredemo
  template:
    metadata:
      labels:
        app: dotnetcoredemo
    spec:
      containers:
      - name: dotnetcoredemo
        image: futugyousuzu/k8s-dotnetcore-demo-0320:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

