{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello-golang.serviceAccountName" . }}
  labels:
{{ include "hello-golang.labels" . | nindent 4 }}
{{- end -}}
