apiVersion: v1 
kind: Secret
metadata:
 name: mysecret
type: Opaque
data: 
 password: bXlzZWNyZXQ=
 username: bXlzZWNyZXQ=


---
apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod
  labels:
    name: mysecretpod
spec:
  containers:
  - name: mysecretpod
    image: redis
    resources:
      limits:
        memory: "10Mi"
        cpu: "100m"
    ports:
      - containerPort: 6379
    volumeMounts:
      - mountPath: "/etc/too"
        name: foo
        readOnly: true
  volumes:
    - name: foo
      secret:
          secretName: mysecret
