# cluster-config.yml
# https://kind.sigs.k8s.io/docs/user/using-wsl2/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP