apiVersion: v1
kind: Service
metadata:
  name: golangdemo
spec:
  type: LoadBalancer 
  selector:
    app: golangdemo
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golangdemo
  template:
    metadata:
      labels:
        app: golangdemo
    spec:
      containers:
      - name: golangdemo
        image: futugyousuzu/go-web-test-200316:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

