---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.demo.welcome.domain
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.demo.welcome.domain
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.demo.welcome.domain
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.demo.welcome.domain
  resources:
  - welcomes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.demo.welcome.domain
  resources:
  - welcomes/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.demo.welcome.domain
  resources:
  - welcomes/status
  verbs:
  - get
  - patch
  - update
