# permissions for end users to view welcomes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: welcome-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: welcome
    app.kubernetes.io/part-of: welcome
    app.kubernetes.io/managed-by: kustomize
  name: welcome-viewer-role
rules:
- apiGroups:
  - webapp.demo.welcome.domain
  resources:
  - welcomes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.demo.welcome.domain
  resources:
  - welcomes/status
  verbs:
  - get
